stages:
  - build
  - test
  - deploy

default:
  image: openjdk:15
  before_script:
    - [ -f .gradlecache ] && mv .gradlecache /root/.gradle
    - chmod +x gradlew
  after_script:
    - cp /root/.gradle .gradlecache
  tags:
    - docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradlecache
    - .gradle

build:
  stage: build
  script:
    - ./gradlew publishToMavenLocal
    - ls -la /root/.gradle
    - ls -lRa /root
  artifacts:
    paths:
      - gradle-versioning-plugin/build
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew test

publish:
  stage: deploy
  only:
    - main
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - gradle-versioning-plugin/build/libs/*.jar
    expire_in: 1 month