stages:
  - build
  - test
  - visualize
  - deploy

default:
  image: openjdk:15
  before_script:
    - mkdir .gradlecache
    - mv .gradlecache /root/.gradle
    - chmod +x gradlew
  after_script:
    - cp -r /root/.gradle .gradlecache
  tags:
    - docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradlecache
    - .gradle

build:
  stage: build
  script:
    - ./gradlew publishToMavenLocal
  artifacts:
    paths:
      - plugin-backgrounds/build
      - plugin-keygen/build
      - plugin-versioning/build
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' plugin-keygen/build/reports/jacoco/test/jacocoTestReport.csv
  artifacts:
    paths:
      - plugin-keygen/build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit:
        - plugin-keygen/build/test-results/test/**/TEST-*.xml

coverage-plugin-keygen:
  stage: visualize
  image: haynes/jacoco2cobertura:1.0.4
  script:
    - 'python /opt/cover2cover.py plugin-keygen/build/reports/jacoco/test/jacocoTestReport.xml src/main/java > plugin-keygen/build/cobertura.xml'
    - 'python /opt/source2filename.py plugin-keygen/build/cobertura.xml'
  needs: ["test"]
  dependencies:
    - test
  artifacts:
    reports:
      cobertura: plugin-keygen/build/cobertura.xml

publish:
  stage: deploy
  only:
    - main
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - gradle-versioning-plugin/build/libs/*.jar
    expire_in: 1 month