package de.menkalian.vela.plain

import de.menkalian.vela.gradle.KeyObjectExtension
import java.io.File

class ClassWriter(clazz: String, pckg: String, config: KeyObjectExtension) {
    private val target: File

    init {
        // Make Parent directory
        val parent = File(File(config.targetDir), pckg.replace('.', '/'))
        parent.mkdirs()

        target = File(parent, "$clazz.java")
        if (target.exists())
            target.delete()
        target.createNewFile()

        // write package
        target.writeText(
            "package $pckg;\n\n" +
                    "/*GENERATED BY VELA*/\n\n"
        )
    }

    fun writeText(text: String) {
        target.appendText(text)
    }
}