name: Release

on:
  push:
    tags:
      - 'release-*.*.*'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.menkalian.de

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
